# Generated by Django 3.1.5 on 2021-02-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
